const ParamMap: Readonly<Record<number, string>> = {
	/* 'free' params omitted */
	0: 'Controller',
	1: 'PitchBend',
	2: 'MonoAftertouch',
	3: 'Prg-Change',
	4: 'PolyAftertouch',
	5: 'Note-On',
	6: 'Note-Off',
	8: 'RPN0_MSB',
	9: 'RPN0_LSB',
	10: 'RPN1_MSB',
	11: 'RPN1_LSB',
	14: 'RPN127_MSB',
	15: 'RPN127_LSB',
	16: 'NRPN0_MSB',
	17: 'NRPN0_LSB',
	18: 'NRPN1_MSB XG_Multi/GS',
	19: 'NRPN1_LSB XG_Multi/GS',
	20: 'NRPN8_MSB',
	21: 'NRPN8_LSB',
	22: 'NRPN9_MSB',
	23: 'NRPN9_LSB',
	24: 'NRPN10_MSB',
	25: 'NRPN10_LSB',
	26: 'NRPN20_MSB XG Drum Instr. Cutoff',
	27: 'NRPN20_LSB XG Drum Instr. Cutoff',
	28: 'NRPN21_MSB XG Drum Instr. Resonance',
	29: 'NRPN21_LSB XG Drum Instr. Resonance',
	30: 'NRPN22_MSB XG Drum Instr. EG Attack',
	31: 'NRPN22_LSB XG Drum Instr. EG Attack',
	32: 'NRPN23_MSB XG Drum Instr. EG Decay',
	33: 'NRPN23_LSB XG Drum Instr. EG Decay',
	34: 'NRPN24_MSB XG/GS Drum Instr. Pitch Coarse',
	35: 'NRPN24_LSB XG/GS Drum Instr. Pitch Coarse',
	36: 'NRPN25_MSB XG Drum Instr. Pitch Fine',
	37: 'NRPN25_LSB XG Drum Instr. Pitch Fine',
	38: 'NRPN26_MSB XG/GS Drum Instr. Level',
	39: 'NRPN26_LSB XG/GS Drum Instr. Level', 
	40: 'NRPN28_MSB XG/GS Drum Instr. Panorama',
	41: 'NRPN28_LSB XG/GS Drum Instr. Panorama',
	42: 'NRPN29_MSB XG/GS Drum Instr. Reverb Send',
	43: 'NRPN29_LSB XG/GS Drum Instr. Reverb Send',
	44: 'NRPN30_MSB XG/GS Drum Instr. Chorus Send',
	45: 'NRPN30_LSB XG/GS Drum Instr. Chorus Send',
	46: 'NRPN31_MSB XG/GS Drum Instr.Variation/Delay Send',
	47: 'NRPN31_LSB XG/GS Drum Instr.Variation/Delay Send',
	48: 'NRPN32_MSB',
	49: 'NRPN32_LSB',
	50: 'NRPN33_MSB',
	51: 'NRPN33_LSB',
	52: 'NRPN99_MSB',
	53: 'NRPN99_LSB',
	54: 'NRPN100_MSB',
	55: 'NRPN100_LSB',
	56: 'NRPN102_MSB',
	57: 'NRPN102_LSB',
	58: 'NRPN120_MSB EMU ABS',
	59: 'NRPN120_LSB EMU ABS',
	60: 'NRPN127_MSB SB AWE 32/64',
	61: 'NRPN127_LSB SB AWE 32/64',
	64: 'XG-DRUM (SetupNr=Chn) Pitch Coarse',
	65: 'XG-DRUM (SetupNr=Chn) Pitch Fine',
	66: 'XG-DRUM (SetupNr=Chn) Level',
	67: 'XG-DRUM (SetupNr=Chn) Alternate Group',
	68: 'XG-DRUM (SetupNr=Chn) Panorama',
	69: 'XG-DRUM (SetupNr=Chn) Reverb Send',
	70: 'XG-DRUM (SetupNr=Chn) Chorus Send',
	71: 'XG-DRUM (SetupNr=Chn) Variation Send',
	72: 'XG-DRUM (SetupNr=Chn) Key Assign',
	73: 'XG-DRUM (SetupNr=Chn) Rcv Note Off',
	74: 'XG-DRUM (SetupNr=Chn) Rcv Note On',
	75: 'XG-DRUM (SetupNr=Chn) Cutoff Freq.',
	76: 'XG-DRUM (SetupNr=Chn) Resonance',
	77: 'XG-DRUM (SetupNr=Chn) EG Attack Rate',
	78: 'XG-DRUM (SetupNr=Chn) EG Decay1 Rate',
	79: 'XG-DRUM (SetupNr=Chn) EG Decay2 Rate',
	80: 'XG Multipart',
	81: 'XG AD',
	82: 'XG-Effect',
	83: 'XG-Effect 2Byte',
	84: 'XG-Reverb Type',
	85: 'XG-Chorus Type',
	86: 'XG-Variation Type',
	87: 'XG-EQ',
	88: 'XG-Insertion1',
	127: 'No-Event'
}

export default ParamMap